name:            optics-thesis
version:         0.1.0.0
author:          Roel Hemerik
maintainer:      haskell@roelweb.com
copyright:       Roel Hemerik


description:     Contains a concrete implementation and examples of optics.

dependencies:
  - base >= 4.7 && < 5
  - containers
  - directory
  - filepath
  - lens
  - generic-lens
  - pointed
  - optics
  - optics-core
  - aeson
  - profunctors
  - comonad
  - lattices
  - yaml
  - data-default
  - bytestring
  - text
  - wreq
  - vector-sized
  - semigroupoids
  - distributive
  - megaparsec
  - modern-uri
  - exceptions
  - mtl
  - transformers
  - prettyprinter
  - template-haskell

default-extensions:
  - AllowAmbiguousTypes
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveGeneric
  - DefaultSignatures
  - DuplicateRecordFields
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - ImplicitParams
  - IncoherentInstances
  - KindSignatures
  - LambdaCase
  - LiberalTypeSynonyms
  - MonoLocalBinds
  - MultiParamTypeClasses
  - NoMonomorphismRestriction
  - OverloadedStrings
  - OverloadedLabels
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TemplateHaskell
  - TemplateHaskellQuotes
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - UndecidableInstances
  - UndecidableSuperClasses

library:
  source-dirs: src
